(** OCaml FFI stub generation for EverParse-produced C validators.

    [Wire_stubs] is the optional bridge back into OCaml: given exported
    {!Wire.C.Raw.struct_} values, it generates C stubs and matching OCaml
    [external] declarations so OCaml code can call EverParse-generated
    validators.

    Most users only need this when they want to reuse generated C from OCaml for
    performance or differential testing. Embedded C consumers can stay on the
    {!Wire.C}/{!Wire_3d} path without using [Wire_stubs]. *)

val everparse_name : string -> string
(** [everparse_name name] returns the EverParse-normalized identifier for a
    struct name. Delegates to {!Wire_3d.everparse_name}. *)

val ml_type_of : 'a Wire.typ -> string
(** [ml_type_of typ] returns the OCaml type name for a wire type: ["int"] for
    all integer types that fit in an OCaml [int] (uint8 through uint63,
    bitfields), ["int64"] for uint64. *)

val to_c_stubs : Wire.C.Raw.struct_ list -> string
(** [to_c_stubs structs] generates a C file with OCaml FFI stubs that call
    EverParse-generated validators. For each struct [Foo], generates:
    - Validation stub [caml_wire_foo_check] calling [Validate] directly

    The generated C code includes the EverParse headers and sources. Compile
    with [-I <schema_dir>] to find them. EverParse identifier normalization is
    handled automatically. *)

val to_ml_stubs : Wire.C.Raw.struct_ list -> string
(** [to_ml_stubs structs] generates OCaml [external] declarations matching the C
    stubs from {!to_c_stubs}. For each struct [Foo], generates:
    {[
      external foo_check : bytes -> bool = "caml_wire_foo_check"
    ]} *)

val to_ml_stub_name : Wire.C.Raw.struct_ -> string
(** [to_ml_stub_name s] returns the lowercase filename stem for the generated
    stub file (e.g., ["foo"] for struct [Foo]). The corresponding OCaml module
    is [Foo]. *)

val to_ml_stub : Wire.C.Raw.struct_ -> string
(** [to_ml_stub s] generates a flat OCaml stub module for a single struct:
    {[
      (* Generated by wire *)
      external check : bytes -> bool = "caml_wire_foo_check"
    ]} *)
